// scripts/generate-vfs.js
const fs = require("fs");
const path = require("path");

const fontsDir = path.resolve(__dirname, "../public/fonts"); 
const outFile = path.resolve(__dirname, "../src/pdf/vfs_fonts.js"); 

if (!fs.existsSync(fontsDir)) {
  console.error("Fonts directory not found:", fontsDir);
  process.exit(1);
}

const files = fs.readdirSync(fontsDir).filter(f => /\.(ttf|otf|woff|woff2)$/i.test(f));
if (files.length === 0) {
  console.error("No font files found in", fontsDir);
  process.exit(1);
}

const vfsEntries = files.map(file => {
  const filePath = path.join(fontsDir, file);
  const base64 = fs.readFileSync(filePath).toString("base64");
  return `  "${file}": "${base64}"`;
}).join(",\n");

const content = `// This file is generated by scripts/generate-vfs.js
// Do not edit by hand.
const vfs = {
${vfsEntries}
};

export default vfs;
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, "utf8");
console.log("✅ vfs generated to", outFile);
